language: go
go: 
    - 1.5.1

env:
    - TEST_DIR=canonical
    - TEST_DIR=concurrent
    - TEST_DIR=context
    - TEST_DIR=convey
    - TEST_DIR=handler
    - TEST_DIR=hash
    - TEST_DIR=health
    - TEST_DIR=jwt/key
    - TEST_DIR=logging
    - TEST_DIR=server
    - TEST_DIR=types

before_install:
    - sudo pip install --user codecov

script:
    - cd $TEST_DIR && go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
