language: go

go:
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master

before_install:
  - curl -s https://codecov.io/bash > codecov.sh	
  - chmod 755 ./codecov.sh

install:
  - GO111MODULE=on go mod vendor

script:
  - go test ./... -race -coverprofile=coverage.txt 
  - ./codecov.sh
