language: go

go:
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master

install:
  - GO111MODULE=on go mod vendor

script:
  - go test ./... -race -cover
