language: go
go: 
    - 1.7.3

before_install:
    - sudo pip install --user codecov
    - mkdir -p $GOPATH/bin
    - curl https://glide.sh/get | sh
    - curl -s https://codecov.io/bash > codecov.sh
    - chmod 755 ./codecov.sh

install:
    - glide install

script:
    - for package in $(go test ./... | grep -v vendor); do
    -    echo $package
    - done
